# 基础镜像
FROM redis
# author
MAINTAINER yuji

# 挂载目录
VOLUME /home/yuji/redis
# 创建目录
RUN mkdir -p /home/yuji/redis
# 指定路径
WORKDIR /home/yuji/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/yuji/redis/redis.conf
