# 基础镜像
FROM nginx
# author
MAINTAINER yuji

# 挂载目录
VOLUME /home/yuji/projects/yuji-ui
# 创建目录
RUN mkdir -p /home/yuji/projects/yuji-ui
# 指定路径
WORKDIR /home/yuji/projects/yuji-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/yuji/projects/yuji-ui
