# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER yuji

# 挂载目录
VOLUME /home/yuji
# 创建目录
RUN mkdir -p /home/yuji
# 指定路径
WORKDIR /home/yuji
# 复制jar文件到路径
COPY ./jar/yuji-gateway.jar /home/yuji/yuji-gateway.jar
# 启动网关服务
ENTRYPOINT ["java","-jar","yuji-gateway.jar"]